Repository nmshd/app, pull requests merged in 2024-12, with the labels that each got.

#341 Simplify account in deletion requests
  .vscode/settings.json
  apps/enmeshed/lib/account/account_screen.dart
  apps/enmeshed/lib/core/utils/account_utils.dart
  apps/enmeshed/lib/core/widgets/restore_profile.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/onboarding/onboarding_account.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_and_choose_next.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_or_identity.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/should_delete_identity.dart
  apps/enmeshed/lib/profiles/profile/modals/restore_profile/restore_identity_modal.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
  apps/enmeshed/lib/profiles/profile/widgets/deletion_profile_card.dart
  apps/enmeshed/lib/splash_screen.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/lib/src/services/account_services.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: refactoring

#347 Display warning if file to upload is too large
  apps/enmeshed/lib/core/widgets/upload_file.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/pubspec.lock
Labels: bug

#353 Add release template
  .github/release.yml
  .github/workflows/check-pr.yml
Labels: chore

#355 Migrate to Flutter 3.27 and Dart 3.6
  apps/connector_ui/pubspec.lock
  apps/connector_ui/pubspec.yaml
  apps/enmeshed/.gitignore
  apps/enmeshed/android/app/build.gradle
  apps/enmeshed/android/app/src/main/AndroidManifest.xml
  apps/enmeshed/android/settings.gradle
  apps/enmeshed/ios/Runner/Info.plist
  apps/enmeshed/lib/account/home/widgets/info_container.dart
  apps/enmeshed/lib/account/mailbox/send_mail_screen/send_mail_screen.dart
  apps/enmeshed/lib/core/modals/enter_password/pin_input.dart
  apps/enmeshed/lib/core/widgets/modal_loading_overlay.dart
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
  apps/enmeshed/lib/core/widgets/restore_profile_container.dart
  apps/enmeshed/lib/core/widgets/scanner_view/scanner_entry.dart
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/onboarding/onboarding_account.dart
  apps/enmeshed/lib/onboarding/onboarding_information.dart
  apps/enmeshed/lib/profiles/device/device_detail/device_detail_screen.dart
  apps/enmeshed/lib/profiles/device/widgets/device_onboarding.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
  apps/enmeshed/lib/profiles/profile/widgets/deletion_profile_card.dart
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
  packages/connector_sdk/pubspec.yaml
  packages/enmeshed_runtime_bridge/pubspec.yaml
  packages/enmeshed_types/pubspec.yaml
  packages/identity_recovery_kit/example/pubspec.lock
  packages/identity_recovery_kit/pubspec.yaml
  packages/renderers/pubspec.yaml
  packages/value_renderer/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: chore

#357 Upgrade runtime
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
  packages/enmeshed_runtime_bridge/.gitignore
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/identity_recovery_kits_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/relationships_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test/services/facades/transport_test.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/identity_recovery_kits_facade.dart
  packages/enmeshed_runtime_bridge/lib/src/services/transport_services.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/analysis_options.yaml
  packages/enmeshed_types/lib/src/common/password_protection.g.dart
  packages/enmeshed_types/lib/src/contents/attribute_query/attribute_query.g.dart
  packages/enmeshed_types/lib/src/contents/render_hints.g.dart
  packages/enmeshed_types/lib/src/contents/value_hints.g.dart
  packages/enmeshed_types/lib/src/dtos/attribute_tag_collection.dart
  packages/enmeshed_types/lib/src/dtos/attribute_tag_collection.g.dart
  packages/enmeshed_types/lib/src/dtos/device.dart
  packages/enmeshed_types/lib/src/dtos/dtos.dart
  packages/enmeshed_types/lib/src/dtos/identity_deletion_process.g.dart
  packages/enmeshed_types/lib/src/dtos/local_attribute_share_info.g.dart
  packages/enmeshed_types/lib/src/dtos/message.g.dart
  packages/enmeshed_types/lib/src/dtos/message_with_attachments.g.dart
  packages/enmeshed_types/lib/src/dtos/relationship.g.dart
  packages/enmeshed_types/lib/src/dtos/relationship_audit_log_entry.g.dart
  packages/enmeshed_types/lib/src/dtos/setting.g.dart
  packages/enmeshed_types/lib/src/dvos/common/dvo_error.g.dart
  packages/enmeshed_types/lib/src/dvos/common/dvo_warning.g.dart
  packages/enmeshed_types/lib/src/dvos/consumption/local_attribute_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/consumption/local_attribute_listener_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/consumption/local_request_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/consumption/peer_relationship_template_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/consumption/processed_attribute_query_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/content/attribute_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/content/attribute_query_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/content/message_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/content/request_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/content/response_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/transport/file_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/transport/identity_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/transport/message_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/transport/relationship_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/transport/relationship_template_dvo.g.dart
  packages/enmeshed_types/lib/src/responses/backbone_compatibility.g.dart
  packages/enmeshed_types/test/dtos/device_test.dart
Labels: dependencies

#360 Delete obsolete local accounts on app startup
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_or_identity_modal.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/identity_deletion_processes_facade_test.dart
  packages/enmeshed_runtime_bridge/lib/src/services/account_services.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/identity_deletion_processes_facade.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: enhancement

#361 Remove unused feature flags
  apps/enmeshed/lib/account/app_drawer/drawer_main_page.dart
  apps/enmeshed/lib/account/home/home.dart
  apps/enmeshed/lib/account/home/widgets/home_widgets.dart
  apps/enmeshed/lib/account/home/widgets/news_container.dart
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
Labels: chore

#362 Add delete now button in debug mode
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_or_identity_modal.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/should_delete_identity.dart
Labels: chore

#363 Discoverable Identities
  apps/enmeshed/lib/account/contacts/contacts_view.dart
  apps/enmeshed/lib/account/contacts/widgets/discoverable_identities.dart
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: enhancement

#364 Local Data Deletion Buttons
  apps/enmeshed/assets/svg/confirm_local_data_deletion.svg
  apps/enmeshed/lib/core/modals/delete_local_data.dart
  apps/enmeshed/lib/core/modals/modals.dart
  apps/enmeshed/lib/core/modals/restore_identity.dart
  apps/enmeshed/lib/core/widgets/local_data_deletion/delete_data_now_card.dart
  apps/enmeshed/lib/core/widgets/local_data_deletion/deletion_profile_card.dart
  apps/enmeshed/lib/core/widgets/local_data_deletion/local_data_deletion.dart
  apps/enmeshed/lib/core/widgets/restore_profile_container.dart
  apps/enmeshed/lib/core/widgets/widgets.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/onboarding/onboarding_account.dart
  apps/enmeshed/lib/onboarding/widgets/profiles_in_deletion_container.dart
  apps/enmeshed/lib/profiles/profile/modals/modals.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
  apps/enmeshed/lib/profiles/profile/widgets/profile_card.dart
  apps/enmeshed/pubspec.lock
Labels: enhancement

#368 Display Tags
  apps/enmeshed/lib/account/contacts/contact_exchanged_attributes_screen.dart
  apps/enmeshed/lib/account/contacts/contact_shared_files_screen.dart
  apps/enmeshed/lib/account/contacts/widgets/contact_shared_files.dart
  apps/enmeshed/lib/account/mailbox/send_mail_screen/widgets/attachments_list.dart
  apps/enmeshed/lib/account/my_data/all_data/all_data_screen.dart
  apps/enmeshed/lib/account/my_data/all_data/attribute_detail_screen.dart
  apps/enmeshed/lib/account/my_data/data_details_screen.dart
  apps/enmeshed/lib/account/my_data/file/file_detail_screen.dart
  apps/enmeshed/lib/account/my_data/file/files_screen.dart
  apps/enmeshed/lib/account/my_data/filtered_data_screen.dart
  apps/enmeshed/lib/account/my_data/initial_creation/my_data_initial_creation_screen.dart
  apps/enmeshed/lib/core/core.dart
  apps/enmeshed/lib/core/modals/create_attribute.dart
  apps/enmeshed/lib/core/modals/succeed_attribute.dart
  apps/enmeshed/lib/core/utils/attribute_utils.dart
  apps/enmeshed/lib/core/widgets/file_item.dart
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
  apps/enmeshed/lib/core/widgets/upload_file.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
Labels: enhancement

#367 Create Identity Recovery Kits
  apps/enmeshed/analysis_options.yaml
  apps/enmeshed/assets/svg/create_recovery_kit.svg
  apps/enmeshed/assets/svg_without_transforming/triangle.svg
  apps/enmeshed/ios/Podfile.lock
  apps/enmeshed/lib/account/account_screen.dart
  apps/enmeshed/lib/account/app_drawer/drawer_hints_page.dart
  apps/enmeshed/lib/account/contacts/contacts_view.dart
  apps/enmeshed/lib/account/contacts/widgets/discoverable_identities.dart
  apps/enmeshed/lib/account/home/widgets/add_contact_or_device_container.dart
  apps/enmeshed/lib/account/home/widgets/complete_profile_container.dart
  apps/enmeshed/lib/core/modals/create_recovery_kit/create_recovery_kit.dart
  apps/enmeshed/lib/core/modals/create_recovery_kit/enter_password.dart
  apps/enmeshed/lib/core/modals/create_recovery_kit/save_or_print_recovery_kit.dart
  apps/enmeshed/lib/core/modals/delete_local_data.dart
  apps/enmeshed/lib/core/modals/enter_password/enter_password.dart
  apps/enmeshed/lib/core/modals/enter_password/password_input.dart
  apps/enmeshed/lib/core/modals/modals.dart
  apps/enmeshed/lib/core/utils/settings_utils.dart
  apps/enmeshed/lib/core/utils/ten_tap_detector.dart
  apps/enmeshed/lib/core/widgets/information_container.dart
  apps/enmeshed/lib/core/widgets/instructions_screen.dart
  apps/enmeshed/lib/core/widgets/local_data_deletion/delete_data_now_card.dart
  apps/enmeshed/lib/core/widgets/local_data_deletion/deletion_profile_card.dart
  apps/enmeshed/lib/core/widgets/modal_loading_overlay.dart
  apps/enmeshed/lib/core/widgets/scan_screen.dart
  apps/enmeshed/lib/core/widgets/widgets.dart
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/onboarding/onboarding_account.dart
  apps/enmeshed/lib/onboarding/onboarding_welcome.dart
  apps/enmeshed/lib/profiles/device/devices_overview/devices_screen.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_or_identity.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_or_identity_modal.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/should_delete_identity.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
  apps/enmeshed/lib/profiles/profile/widgets/profile_card.dart
  apps/enmeshed/lib/splash_screen.dart
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/identity_recovery_kit/example/lib/main.dart
  packages/identity_recovery_kit/lib/src/pdf_generator.dart
Labels: enhancement
