Repository nmshd/app, pull requests merged in 2025-08, with the labels that each got.

#750 Padding to native buttons is too small
  apps/enmeshed/lib/account/my_data/file/modals/select_file_tags.dart
  apps/enmeshed/lib/account/my_data/file/modals/select_file_types.dart
  apps/enmeshed/lib/l10n/app_de.arb
Labels: bug

#757 Disabled text is too bright
  apps/enmeshed/lib/account/my_data/filtered_data_screen.dart
  apps/enmeshed/lib/core/widgets/message_list_tile.dart
Labels: bug

#759 Checkbox is hidden for decided TransferFileOwnershipRequestItem
  packages/renderers/lib/src/request/request_item_renderer/transfer_file_ownership_request_item_renderer.dart
Labels: bug

#761 Paddings and colors in my data are incorrect
  apps/enmeshed/lib/account/my_data/filtered_data_screen.dart
  apps/enmeshed/lib/account/my_data/my_data_view.dart
Labels: bug

#764 Give feedback button is overlapped by the navigation buttons
  apps/enmeshed/lib/main.dart
Labels: bug

#769 Allow switching log level from debug screen
  apps/enmeshed/lib/core/models/log_level_model.dart
  apps/enmeshed/lib/core/models/models.dart
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/main.dart
Labels: enhancement

#771 Created attribute is not used in ReadAttributeRequestItemRenderer
  packages/renderers/lib/src/request/request_item_renderer/read_attribute_request_item_renderer.dart
Labels: bug

#772 Place scanner buttons properly
  apps/enmeshed/lib/core/widgets/scanner_view/scanner_entry.dart
Labels: bug

#775 Use tearoff for context.pop
  apps/enmeshed/lib/account/app_drawer/drawer_hints_page.dart
  apps/enmeshed/lib/account/app_drawer/drawer_main_page.dart
  apps/enmeshed/lib/account/app_drawer/drawer_notifications_page.dart
  apps/enmeshed/lib/account/app_drawer/drawer_theme_page.dart
  apps/enmeshed/lib/account/mailbox/modals/select_contact_filter.dart
  apps/enmeshed/lib/account/mailbox/send_mail_screen/widgets/quit_creating_message_dialog.dart
  apps/enmeshed/lib/account/my_data/file/modals/select_file_tags.dart
  apps/enmeshed/lib/account/my_data/file/modals/select_file_types.dart
  apps/enmeshed/lib/account/my_data/initial_creation/my_data_initial_creation_screen.dart
  apps/enmeshed/lib/core/modals/create_attribute.dart
  apps/enmeshed/lib/core/modals/enter_password/enter_password.dart
  apps/enmeshed/lib/core/modals/feedback/feedback_error_dialog.dart
  apps/enmeshed/lib/core/modals/feedback/feedback_success_dialog.dart
  apps/enmeshed/lib/core/modals/succeed_attribute.dart
  apps/enmeshed/lib/core/widgets/create_profile.dart
  apps/enmeshed/lib/core/widgets/instructions_screen.dart
  apps/enmeshed/lib/core/widgets/upload_file.dart
  apps/enmeshed/lib/profiles/device/device_detail/widgets/delete_device_sheet.dart
  apps/enmeshed/lib/profiles/device/device_detail/widgets/edit_device.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/deleting_profile.dart
  apps/enmeshed/lib/profiles/profile/modals/edit_profile.dart
  apps/enmeshed/lib/profiles/profile/select_profile_dialog.dart
  packages/renderers/lib/src/request/request_item_renderer/consent_request_item_renderer.dart
Labels: refactoring

#781 Migrate to Flutter 3.35
  apps/enmeshed/android/app/build.gradle
  apps/enmeshed/ios/Flutter/AppFrameworkInfo.plist
  apps/enmeshed/ios/Podfile.lock
  apps/enmeshed/ios/Runner.xcodeproj/project.pbxproj
  apps/enmeshed/l10n.yaml
  apps/enmeshed/lib/account/app_drawer/drawer_theme_page.dart
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
  packages/enmeshed_runtime_bridge/integration_test_runner/android/app/build.gradle
  packages/enmeshed_runtime_bridge/integration_test_runner/ios/Flutter/AppFrameworkInfo.plist
  packages/enmeshed_runtime_bridge/integration_test_runner/ios/Podfile
  packages/enmeshed_runtime_bridge/integration_test_runner/ios/Podfile.lock
  packages/enmeshed_runtime_bridge/integration_test_runner/ios/Runner.xcodeproj/project.pbxproj
  packages/enmeshed_runtime_bridge/integration_test_runner/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/enmeshed_runtime_bridge/integration_test_runner/pubspec.lock
  packages/enmeshed_runtime_bridge/integration_test_runner/pubspec.yaml
  packages/enmeshed_runtime_bridge/pubspec.yaml
  packages/enmeshed_types/pubspec.yaml
  packages/enmeshed_ui_kit/pubspec.yaml
  packages/identity_recovery_kit/example/.gitignore
  packages/identity_recovery_kit/example/ios/Flutter/AppFrameworkInfo.plist
  packages/identity_recovery_kit/example/ios/Podfile
  packages/identity_recovery_kit/example/ios/Podfile.lock
  packages/identity_recovery_kit/example/ios/Runner.xcodeproj/project.pbxproj
  packages/identity_recovery_kit/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/identity_recovery_kit/example/pubspec.lock
  packages/identity_recovery_kit/example/pubspec.yaml
  packages/identity_recovery_kit/pubspec.yaml
  packages/renderers/lib/src/request/request_item_renderer/consent_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/widgets/manual_decision_required.dart
  packages/renderers/pubspec.yaml
  packages/value_renderer/lib/src/inputs/dropdown_select_input.dart
  packages/value_renderer/lib/src/inputs/radio_input.dart
  packages/value_renderer/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: refactoring

#782 Make openid4vc presentation request clickable inside messages
  apps/enmeshed/android/app/src/main/AndroidManifest.xml
  apps/enmeshed/ios/Runner/Info.plist
  apps/enmeshed/lib/account/mailbox/message_detail_screen.dart
Labels: enhancement

#791 Update release naming to not include `enmeshed-v`
  codemagic.yaml
Labels: ci

#794 Allow composing RelationshipAttributes in ReadAttributeRequestItemRenderer
  apps/enmeshed/lib/account/my_data/all_data/all_data_screen.dart
  apps/enmeshed/lib/account/my_data/data_details_screen.dart
  apps/enmeshed/lib/account/my_data/filtered_data_screen.dart
  apps/enmeshed/lib/core/modals/compose_relationship_attribute.dart
  apps/enmeshed/lib/core/modals/create_identity_attribute.dart
  apps/enmeshed/lib/core/modals/modals.dart
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
  packages/enmeshed_types/lib/src/dtos/local_attribute.dart
  packages/enmeshed_types/test/dtos/local_attribute_test.dart
  packages/renderers/lib/src/attribute/attribute_renderer.dart
  packages/renderers/lib/src/attribute/relationship_attribute_value_renderer.dart
  packages/renderers/lib/src/request/open_attribute_switcher_function.dart
  packages/renderers/lib/src/request/request_item_group_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/read_attribute_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/response/response_item_group_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/response/response_item_renderer.dart
  packages/renderers/lib/src/request/request_renderer.dart
  packages/renderers/lib/src/utils/compose_relationship_attribute_value.dart
  pubspec.lock
Labels: enhancement

#803 Fix typo
  apps/enmeshed/lib/account/my_data/all_data/all_data_screen.dart
  apps/enmeshed/lib/account/my_data/data_details_screen.dart
  apps/enmeshed/lib/account/my_data/filtered_data_screen.dart
  apps/enmeshed/lib/core/modals/create_identity_attribute.dart
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
Labels: chore

#804 Focused borders have the wrong color
  apps/enmeshed/lib/core/modals/create_recovery_kit/enter_password.dart
  apps/enmeshed/lib/core/widgets/create_profile.dart
  apps/enmeshed/lib/core/widgets/profile_picture.dart
  apps/enmeshed/lib/core/widgets/scanner_view/scanner_entry.dart
  apps/enmeshed/lib/onboarding/device_onboarding_screen.dart
  apps/enmeshed/lib/profiles/device/device_detail/widgets/edit_device.dart
  apps/enmeshed/lib/profiles/device/modals/create_device.dart
  apps/enmeshed/lib/profiles/profile/modals/edit_profile.dart
  packages/renderers/lib/src/request/request_item_renderer/read_attribute_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/widgets/manual_decision_required.dart
  packages/value_renderer/lib/src/inputs/styles/input_decoration.dart
  packages/value_renderer/lib/src/renderers/complex.dart
Labels: bug
