Repository nmshd/app, pull requests merged in 2025-06, with the labels that each got.

#643 The FAB color is not as in the design
  apps/enmeshed/lib/themes/themes.dart
Labels: bug

#646 The close icon in success snack bars is confusing
  apps/enmeshed/lib/core/utils/account_utils.dart
  apps/enmeshed/lib/core/utils/snackbars.dart
  apps/enmeshed/lib/identity_in_deletion_screen.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/deleting_profile.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
Labels: bug

#650 Encoding android notification color failed
  packages/enmeshed_runtime_bridge/lib/src/enmeshed_runtime.dart
Labels: bug

#655 Increase maximum number of characters within consents and allow loading items using url references
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/js/package-lock.json
  packages/enmeshed_runtime_bridge/js/package.json
Labels: enhancement

#656 Successful URL processing incorrectly handled as error
  apps/enmeshed/lib/onboarding/onboarding_screen.dart
Labels: bug

#658 Bump runtime to support `wasViewed` of Files
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/files_facade_test.dart
  packages/enmeshed_runtime_bridge/js/package-lock.json
  packages/enmeshed_runtime_bridge/js/package.json
  packages/enmeshed_runtime_bridge/lib/src/events/events.dart
  packages/enmeshed_runtime_bridge/lib/src/events/transport/file_was_viewed_event.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/files_facade.dart
  packages/enmeshed_types/lib/src/dtos/file.dart
  packages/enmeshed_types/lib/src/dtos/file.g.dart
  packages/enmeshed_types/lib/src/dvos/transport/file_dvo.dart
  packages/enmeshed_types/lib/src/dvos/transport/file_dvo.g.dart
Labels: dependencies

#664 Uniform appbar spacing
  apps/enmeshed/lib/account/account_screen.dart
  apps/enmeshed/lib/themes/themes.dart
Labels: enhancement

#667 Write logs to files and allow downloading logs as zip
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/main.dart
Labels: enhancement

#671 Webp is marked as unknown file instead of image
  packages/enmeshed_ui_kit/lib/src/widgets/file_icon.dart
Labels: bug

#666 Bump runtime to support `wasViewedAt` of LocalAttributes
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/attributes_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/files_facade_test.dart
  packages/enmeshed_runtime_bridge/js/package-lock.json
  packages/enmeshed_runtime_bridge/js/package.json
  packages/enmeshed_runtime_bridge/lib/src/events/consumption/attribute_was_viewed_at_changed_event.dart
  packages/enmeshed_runtime_bridge/lib/src/events/events.dart
  packages/enmeshed_runtime_bridge/lib/src/events/transport/file_was_viewed_event.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/files_facade.dart
  packages/enmeshed_types/lib/src/dtos/file.dart
  packages/enmeshed_types/lib/src/dtos/file.g.dart
  packages/enmeshed_types/lib/src/dtos/local_attribute.dart
  packages/enmeshed_types/lib/src/dvos/consumption/local_attribute_dvo.dart
  packages/enmeshed_types/lib/src/dvos/consumption/local_attribute_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/transport/file_dvo.dart
  packages/enmeshed_types/lib/src/dvos/transport/file_dvo.g.dart
Labels: dependencies

#672 Remove unused translations
  .github/workflows/test.yml
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  melos.yaml
Labels: chore, ci

#680 Long term request expiry notice is confusing
  apps/enmeshed/lib/account/contacts/widgets/dismissible_contact_item.dart
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: bug

#670 Rework mailbox
  apps/enmeshed/lib/account/account_screen.dart
  apps/enmeshed/lib/account/account_tab_controller.dart
  apps/enmeshed/lib/account/mailbox/mailbox.dart
  apps/enmeshed/lib/account/mailbox/mailbox_filter_controller.dart
  apps/enmeshed/lib/account/mailbox/mailbox_filter_option.dart
  apps/enmeshed/lib/account/mailbox/mailbox_view.dart
  apps/enmeshed/lib/account/mailbox/modals/mailbox_filter_help.dart
  apps/enmeshed/lib/account/mailbox/modals/select_contact_filter.dart
  apps/enmeshed/lib/account/mailbox/modals/select_mailbox_filters.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
Labels: enhancement

#681 Add AttributeWasViewedAtChangedEvent handler
  packages/enmeshed_runtime_bridge/lib/src/javascript_handlers.dart
Labels: enhancement

#686 It is possible to succeed an attribute with an empty value
  apps/enmeshed/lib/core/modals/succeed_attribute.dart
Labels: bug
