Repository nmshd/app, pull requests merged in 2025-02, with the labels that each got.

#422 Use filled tonal buttons to display set filters
  apps/enmeshed/lib/account/account_screen.dart
Labels: enhancement

#421 Handle repository attribute creation errors
  apps/enmeshed/lib/core/modals/create_attribute.dart
  apps/enmeshed/lib/core/utils/attribute_utils.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: enhancement

#427 Skip integration test if runtime bridge was not changed
  .github/workflows/runtime_bridge_integration_tests.yml
Labels: ci

#426 Make links tappable in mail body
  apps/enmeshed/lib/account/mailbox/message_detail_screen.dart
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
Labels: enhancement

#429 Unknown identity is not properly translated
  apps/enmeshed/assets/i18n/de.json
  apps/enmeshed/assets/i18n/en.json
Labels: bug

#425 Runtime init error handling
  apps/enmeshed/assets/svg/backbone_error.svg
  apps/enmeshed/assets/svg/unexpected_error.svg
  apps/enmeshed/lib/core/app_ui_bridge.dart
  apps/enmeshed/lib/error_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/splash_screen.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/lib/src/enmeshed_runtime.dart
  packages/enmeshed_runtime_bridge/natives/src/index.ts
Labels: enhancement

#430 Missing commas in translations
  apps/enmeshed/lib/l10n/app_de.arb
Labels: bug

#431 Update SVGs to be dark mode friendly
  apps/enmeshed/assets/svg/backbone_error.svg
  apps/enmeshed/assets/svg/unexpected_error.svg
Labels: chore

#432 Show proper dialogs for errors during template processing
  apps/enmeshed/lib/core/app_ui_bridge.dart
  apps/enmeshed/lib/core/custom_pages.dart
  apps/enmeshed/lib/core/modals/error_dialog.dart
  apps/enmeshed/lib/core/modals/modals.dart
  apps/enmeshed/lib/core/utils/dialogs.dart
  apps/enmeshed/lib/core/widgets/scan_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/onboarding/onboarding_account.dart
Labels: enhancement

#434 Bump runtime
  .dev/compose.backbone.yml
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/attributes_facade_test.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/dtos/device_shared_secret.dart
  packages/enmeshed_types/lib/src/responses/delete_own_shared_attribute_and_notify_peer.dart
  packages/enmeshed_types/lib/src/responses/delete_own_shared_attribute_and_notify_peer.g.dart
  packages/enmeshed_types/lib/src/responses/delete_peer_shared_attribute_and_notify_owner.dart
  packages/enmeshed_types/lib/src/responses/delete_peer_shared_attribute_and_notify_owner.g.dart
  packages/enmeshed_types/lib/src/responses/delete_third_party_relationship_attribute_and_notify_peer.dart
  packages/enmeshed_types/lib/src/responses/delete_third_party_relationship_attribute_and_notify_peer.g.dart
  packages/enmeshed_types/test/dtos/device_shared_secret_test.dart
Labels: dependencies

#441 Remove wolt from show request certificate modal
  apps/enmeshed/android/.gitignore
  apps/enmeshed/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  apps/enmeshed/lib/account/contacts/modals/request_certificate.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: refactoring

#433 Rework succeed attribute
  apps/enmeshed/lib/core/modals/succeed_attribute.dart
  apps/enmeshed/lib/l10n/app_de.arb
Labels: refactoring

#442 Upgrade Runtime
  README_dev.md
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/files_facade_test.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/files_facade.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/dtos/file.dart
  packages/enmeshed_types/lib/src/dtos/file.g.dart
  packages/enmeshed_types/lib/src/dvos/transport/file_dvo.dart
  packages/enmeshed_types/lib/src/dvos/transport/file_dvo.g.dart
  packages/enmeshed_types/test/dtos/file_test.dart
Labels: dependencies

#446 text is overflowing in ProcessedThirdPartyRelationshipAttributeQueryRenderer
  packages/renderers/lib/src/request/request_item_renderer/decidable/widgets/processed_query_renderer.dart
Labels: bug

#445 Migrate away from synthetic translation package
  .github/workflows/test.yml
  apps/enmeshed/.gitignore
  apps/enmeshed/l10n.yaml
  apps/enmeshed/lib/core/utils/extensions.dart
  apps/enmeshed/lib/main.dart
  apps/enmeshed/pubspec.yaml
  codemagic.yaml
  melos.yaml
Labels: refactoring

#448 FreeTextRequestItem is answered with the wrong response item
  packages/enmeshed_types/lib/src/requests/decide_request/accept_request/free_text.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_free_text_request_item.dart
Labels: bug

#450 Rework UI of use recovery kit flow
  apps/enmeshed/lib/core/modals/create_recovery_kit/enter_password.dart
  apps/enmeshed/lib/core/widgets/information_container.dart
  apps/enmeshed/lib/core/widgets/instructions_screen.dart
  apps/enmeshed/lib/core/widgets/scanner_view/scanner_entry.dart
  apps/enmeshed/lib/main.dart
Labels: enhancement

#436 Use recovery kit flow
  apps/enmeshed/lib/account/home/widgets/complete_profile_container.dart
  apps/enmeshed/lib/core/app_ui_bridge.dart
  apps/enmeshed/lib/core/core.dart
  apps/enmeshed/lib/core/globals.dart
  apps/enmeshed/lib/core/modals/create_recovery_kit/enter_password.dart
  apps/enmeshed/lib/core/modals/error_dialog.dart
  apps/enmeshed/lib/core/utils/settings_utils.dart
  apps/enmeshed/lib/core/utils/snackbars.dart
  apps/enmeshed/lib/core/widgets/information_container.dart
  apps/enmeshed/lib/core/widgets/instructions_screen.dart
  apps/enmeshed/lib/core/widgets/scan_recovery_kit_screen.dart
  apps/enmeshed/lib/core/widgets/scanner_view/scanner_entry.dart
  apps/enmeshed/lib/core/widgets/widgets.dart
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/onboarding/onboarding_account.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
  apps/enmeshed/lib/splash_screen.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/ios/Podfile.lock
  packages/enmeshed_runtime_bridge/integration_test_runner/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/dtos/device_shared_secret.dart
  packages/enmeshed_types/test/contents/token_content/token_content_device_shared_secret_test.dart
  packages/enmeshed_types/test/contents/token_content/token_content_test.dart
  packages/enmeshed_types/test/dtos/device_shared_secret_test.dart
Labels: enhancement

#455 Upgrade the runtime to add support for deleting incoming requests
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/requests_facade_test.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/incoming_requests_facade.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: dependencies

#456 Update scanner entry to match design
  apps/enmeshed/lib/core/widgets/scanner_view/scanner_entry.dart
  apps/enmeshed/lib/l10n/app_de.arb
Labels: enhancement

#453 Create new recovery kit after usage
  apps/enmeshed/lib/account/home/home.dart
  apps/enmeshed/lib/core/modals/create_recovery_kit/create_recovery_kit.dart
  apps/enmeshed/lib/core/utils/settings_utils.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: enhancement

#458 Alignments and sizes are wrong on big screens
  apps/enmeshed/lib/account/app_drawer/app_drawer.dart
  apps/enmeshed/lib/account/home/widgets/complete_profile_container.dart
  apps/enmeshed/lib/core/widgets/information_container.dart
Labels: bug

#457 Rework wording in notifications drawer
  apps/enmeshed/assets/svg/notifications.svg
  apps/enmeshed/lib/account/app_drawer/drawer_hints_page.dart
  apps/enmeshed/lib/account/app_drawer/drawer_main_page.dart
  apps/enmeshed/lib/account/app_drawer/drawer_notifications_page.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: refactoring

#460 Delete attribute bottom sheet is overlapping
  apps/enmeshed/lib/core/modals/delete_attribute.dart
  apps/enmeshed/lib/l10n/app_de.arb
Labels: bug
