Repository nmshd/app, pull requests merged in 2025-03, with the labels that each got.

#451 Check if establishing relationship is possible
  apps/enmeshed/lib/account/contacts/contacts_view.dart
  apps/enmeshed/lib/account/contacts/request_screen.dart
  apps/enmeshed/lib/account/contacts/widgets/dismissible_contact_item.dart
  apps/enmeshed/lib/account/mailbox/message_detail_screen.dart
  apps/enmeshed/lib/core/modals/create_relationship_error_dialog.dart
  apps/enmeshed/lib/core/modals/modals.dart
  apps/enmeshed/lib/core/utils/contact_utils.dart
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: enhancement

#466 Upgrade Runtime to v7 alpha 1
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/requests_facade_test.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/contents/request_item/authentication_request_item.dart
  packages/enmeshed_types/lib/src/dtos/file.dart
  packages/enmeshed_types/lib/src/dtos/file.g.dart
  packages/enmeshed_types/lib/src/dtos/relationship.dart
  packages/enmeshed_types/lib/src/dtos/relationship.g.dart
  packages/enmeshed_types/lib/src/dvos/consumption/decidable_request_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.g.dart
  packages/enmeshed_types/test/contents/request_item/authentication_request_item_test.dart
  packages/enmeshed_types/test/contents/request_item/request_item_derivation_test.dart
  packages/enmeshed_types/test/responses/challenge_validation_result_test.dart
  packages/renderers/test/renderers/request_item_renderer/authentication_request_item_renderer_test.dart
Labels: enhancement, breaking-change

#462 Update relationships screen
  apps/enmeshed/lib/account/contacts/contacts_view.dart
  apps/enmeshed/lib/account/contacts/widgets/contact_detail_header.dart
  apps/enmeshed/lib/account/contacts/widgets/dismissible_contact_item.dart
  apps/enmeshed/lib/account/contacts/widgets/widgets.dart
  apps/enmeshed/lib/core/types/request_or_relationship.dart
  apps/enmeshed/lib/core/types/types.dart
  apps/enmeshed/lib/core/widgets/contact_circle_avatar.dart
  apps/enmeshed/lib/core/widgets/contact_item.dart
  apps/enmeshed/lib/core/widgets/contact_status_text.dart
  apps/enmeshed/lib/core/widgets/widgets.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: enhancement

#471 Upgrade runtime to alpha 4
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/attributes_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/files_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/relationship_templates_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/utils.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/contents/abstract_attribute.dart
  packages/enmeshed_types/lib/src/contents/attribute_query/attribute_query.g.dart
  packages/enmeshed_types/lib/src/contents/attribute_query/identity_attribute_query.dart
  packages/enmeshed_types/lib/src/contents/attribute_query/relationship_attribute_query.dart
  packages/enmeshed_types/lib/src/contents/attribute_query/third_party_relationship_attribute_query.dart
  packages/enmeshed_types/lib/src/contents/identity_attribute.dart
  packages/enmeshed_types/lib/src/contents/relationship_attribute.dart
  packages/enmeshed_types/lib/src/dvos/consumption/processed_attribute_query_dvos.dart
  packages/enmeshed_types/lib/src/dvos/consumption/processed_attribute_query_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/content/attribute_query_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/attribute_query_dvos.g.dart
  packages/enmeshed_types/test/contents/abstract_attribute_test.dart
  packages/enmeshed_types/test/contents/attribute_query/identity_attribute_query_test.dart
  packages/enmeshed_types/test/contents/attribute_query/relationship_attribute_query_test.dart
  packages/enmeshed_types/test/contents/attribute_query/third_party_relationship_attribute_query_test.dart
  packages/enmeshed_types/test/contents/identity_attribute_test.dart
  packages/enmeshed_types/test/contents/relationship_attribute_test.dart
Labels: enhancement

#473 Do-not-show-again text overlaps
  apps/enmeshed/lib/core/widgets/instructions_screen.dart
Labels: bug

#474 Bump backbone to 6.33.0
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
Labels: dependencies

#478 Compromised action
  .github/workflows/runtime_bridge_integration_tests.yml
Labels: ci

#476 Pinned colors in color scheme generation cause too little contrast on some places
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/themes/color_schemes.dart
  packages/enmeshed_ui_kit/lib/src/utils/custom_colors.dart
Labels: bug

#479 Upgrade the Runtime to add TransferFileOwnershipRequestItem
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/contents/request_item/request_item.dart
  packages/enmeshed_types/lib/src/contents/request_item/request_item_derivation.dart
  packages/enmeshed_types/lib/src/contents/request_item/transfer_file_ownership_request_item.dart
  packages/enmeshed_types/lib/src/contents/response_item/response_item.dart
  packages/enmeshed_types/lib/src/contents/response_item/transfer_file_ownership_accept_response_item.dart
  packages/enmeshed_types/lib/src/dvos/consumption/decidable_request_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.g.dart
Labels: dependencies

#480 Simplify custom colors generation
  apps/enmeshed/lib/themes/color_schemes.dart
  apps/enmeshed/lib/themes/custom_colors.dart
  packages/enmeshed_ui_kit/lib/src/utils/custom_colors.dart
Labels: refactoring

#475 User does not receive local notifications
  packages/enmeshed_runtime_bridge/lib/src/enmeshed_runtime.dart
  packages/enmeshed_runtime_bridge/lib/src/javascript_handlers.dart
Labels: bug

#469 Add unified card component
  apps/enmeshed/lib/account/contacts/contacts_view.dart
  apps/enmeshed/lib/account/contacts/widgets/attention_required_banner.dart
  apps/enmeshed/lib/account/contacts/widgets/widgets.dart
  apps/enmeshed/lib/account/home/home.dart
  apps/enmeshed/lib/core/modals/create_recovery_kit/enter_password.dart
  apps/enmeshed/lib/core/widgets/information_container.dart
  apps/enmeshed/lib/core/widgets/instructions_screen.dart
  apps/enmeshed/lib/core/widgets/local_data_deletion/delete_data_now_card.dart
  apps/enmeshed/lib/core/widgets/local_data_deletion/local_data_deletion.dart
  apps/enmeshed/lib/core/widgets/widgets.dart
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/onboarding/widgets/profiles_in_deletion_container.dart
  apps/enmeshed/lib/profiles/device/modals/device_onboarding_safety_note.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
  packages/enmeshed_ui_kit/lib/enmeshed_ui_kit.dart
  packages/enmeshed_ui_kit/lib/src/cards/banner_card.dart
  packages/enmeshed_ui_kit/lib/src/cards/cards.dart
  packages/enmeshed_ui_kit/lib/src/cards/complex_information_card.dart
  packages/enmeshed_ui_kit/lib/src/cards/information_card.dart
Labels: refactoring

#481 Rework contact list monograms
  apps/enmeshed/lib/account/contacts/contacts_view.dart
  apps/enmeshed/lib/account/contacts/widgets/dismissible_contact_item.dart
  apps/enmeshed/lib/core/widgets/contact_item.dart
Labels: bug

#482 Bump backbone to 6.34.2
  .dev/appsettings.override.json
  .dev/compose.backbone.env
Labels: dependencies

#485 Bump runtime to 6.33.0
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: dependencies

#487 Use some new flutter 3.29 features
  apps/enmeshed/lib/themes/color_schemes.dart
  apps/enmeshed/lib/themes/themes.dart
Labels: enhancement

#486 Add tags to AcceptProposeAttributeRequestItemParametersWithExistingAttribute
  packages/enmeshed_types/lib/src/requests/decide_request/accept_request/propose_attribute.dart
  packages/enmeshed_types/test/requests/decide_request/accept_request/propose_attribute_test.dart
Labels: bug

#491 Deserializing a TransferFileOwnershipAcceptResponseItem throws an error
  packages/enmeshed_types/lib/src/contents/response_item/accept_response_item.dart
Labels: bug

#494 Rework message list items
  apps/enmeshed/lib/core/widgets/message_dvo_renderer.dart
Labels: enhancement
