Repository nmshd/app, pull requests merged in 2025-01, with the labels that each got.

#378 Update first step card spacing and text style
  apps/enmeshed/lib/account/home/widgets/complete_profile_container.dart
Labels: bug

#381 Retry processing password protected references for wrong passwords
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  apps/enmeshed/ios/Podfile.lock
  apps/enmeshed/lib/core/app_ui_bridge.dart
  apps/enmeshed/lib/core/modals/delete_local_data.dart
  apps/enmeshed/lib/core/modals/enter_password/enter_password.dart
  apps/enmeshed/lib/core/widgets/scan_screen.dart
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/onboarding/onboarding_account.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/utils.dart
  packages/enmeshed_runtime_bridge/lib/src/javascript_handlers.dart
  packages/enmeshed_runtime_bridge/lib/src/ui_bridge.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_runtime_bridge/natives/src/uiBridge.ts
Labels: enhancement

#382 Add windows support to integration test runner
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/.gitignore
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/CMakeLists.txt
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/flutter/CMakeLists.txt
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/flutter/generated_plugin_registrant.cc
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/flutter/generated_plugin_registrant.h
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/flutter/generated_plugins.cmake
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/CMakeLists.txt
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/Runner.rc
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/flutter_window.cpp
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/flutter_window.h
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/main.cpp
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/resource.h
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/resources/app_icon.ico
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/runner.exe.manifest
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/utils.cpp
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/utils.h
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/win32_window.cpp
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/runner/win32_window.h
Labels: test

#383 Update InAppWebView
  packages/enmeshed_runtime_bridge/integration_test_runner/pubspec.lock
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/flutter/generated_plugin_registrant.cc
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/flutter/generated_plugins.cmake
  packages/enmeshed_runtime_bridge/pubspec.yaml
Labels: dependencies

#386 Hide technical relationship attributes
  apps/enmeshed/lib/account/contacts/contact_exchanged_attributes_screen.dart
  apps/enmeshed/lib/core/widgets/upload_file.dart
  apps/enmeshed/pubspec.lock
Labels: bug

#388 Do not show again in scanner instructions is not respected
  apps/enmeshed/lib/core/utils/settings_utils.dart
  apps/enmeshed/lib/core/widgets/instructions_screen.dart
  apps/enmeshed/lib/main.dart
Labels: bug

#385 Rework contact detail screen
  apps/enmeshed/lib/account/contacts/contact_detail_screen.dart
  apps/enmeshed/lib/account/contacts/modals/modals.dart
  apps/enmeshed/lib/account/contacts/widgets/contact_detail_header.dart
  apps/enmeshed/lib/account/contacts/widgets/contact_detail_icon_bar.dart
  apps/enmeshed/lib/account/contacts/widgets/contact_detail_shared_information.dart
  apps/enmeshed/lib/account/contacts/widgets/contact_status_info_container.dart
  apps/enmeshed/lib/account/contacts/widgets/contact_status_text.dart
  apps/enmeshed/lib/account/contacts/widgets/widgets.dart
  apps/enmeshed/lib/core/utils/contact_utils.dart
  apps/enmeshed/lib/core/utils/dialogs.dart
  apps/enmeshed/lib/core/widgets/contact_circle_avatar.dart
  apps/enmeshed/lib/core/widgets/empty_list_indicator.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/pubspec.lock
Labels: enhancement

#393 Add IdentityDeletionProcesses to ExternalEventReceivedEvent
  packages/enmeshed_runtime_bridge/lib/src/events/app_runtime/external_event_received_event.dart
  packages/enmeshed_runtime_bridge/lib/src/javascript_handlers.dart
Labels: enhancement

#395 Errors during IdentityDeletion are not catched properly
  apps/enmeshed/ios/Podfile.lock
  apps/enmeshed/lib/account/account_screen.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_and_choose_next.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_or_identity_modal.dart
  packages/enmeshed_runtime_bridge/lib/enmeshed_runtime_bridge.dart
Labels: bug

#398 Upgrade runtime
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: dependencies

#401 Android controls overlapping app contents
  apps/enmeshed/lib/account/app_drawer/app_drawer.dart
  apps/enmeshed/lib/account/mailbox/modals/select_mailbox_filters.dart
  apps/enmeshed/lib/account/mailbox/send_mail_screen/widgets/choose_contact.dart
  apps/enmeshed/lib/account/my_data/file/file_detail_screen.dart
  apps/enmeshed/lib/account/my_data/initial_creation/my_data_initial_creation_screen.dart
  apps/enmeshed/lib/core/modals/create_attribute.dart
  apps/enmeshed/lib/core/modals/create_recovery_kit/enter_password.dart
  apps/enmeshed/lib/core/modals/create_recovery_kit/save_or_print_recovery_kit.dart
  apps/enmeshed/lib/core/modals/delete_attribute.dart
  apps/enmeshed/lib/core/modals/delete_local_data.dart
  apps/enmeshed/lib/core/modals/enter_password/enter_password.dart
  apps/enmeshed/lib/core/modals/restore_identity.dart
  apps/enmeshed/lib/core/modals/succeed_attribute.dart
  apps/enmeshed/lib/core/widgets/file_chooser.dart
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
  apps/enmeshed/lib/core/widgets/scanner_view/scanner_entry.dart
  apps/enmeshed/lib/core/widgets/upload_file.dart
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/onboarding/onboarding_create_account.dart
  apps/enmeshed/lib/onboarding/onboarding_information.dart
  apps/enmeshed/lib/onboarding/onboarding_welcome.dart
  apps/enmeshed/lib/profiles/device/device_detail/widgets/delete_device_sheet.dart
  apps/enmeshed/lib/profiles/device/device_detail/widgets/edit_device.dart
  apps/enmeshed/lib/profiles/device/devices_overview/widgets/create_device.dart
  apps/enmeshed/lib/profiles/device/widgets/device_onboarding.dart
  apps/enmeshed/lib/profiles/device/widgets/device_onboarding_safety_note.dart
  apps/enmeshed/lib/profiles/device/widgets/device_onboarding_success.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_and_choose_next.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_or_identity.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/should_delete_identity.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/should_delete_profile.dart
  apps/enmeshed/lib/profiles/profile/modals/edit_profile/edit_profile.dart
  apps/enmeshed/lib/profiles/profile/modals/edit_profile/saving_profile.dart
  apps/enmeshed/lib/profiles/profile/widgets/create_profile.dart
Labels: bug

#403 Add KeyboardAwareSafeArea helper widget
  packages/enmeshed_ui_kit/lib/enmeshed_ui_kit.dart
  packages/enmeshed_ui_kit/lib/src/widgets/keyboard_aware_safe_area.dart
  packages/enmeshed_ui_kit/lib/src/widgets/widgets.dart
Labels: enhancement

#406 Paddings all over the app are varying
  apps/enmeshed/lib/core/widgets/instructions_screen.dart
  apps/enmeshed/lib/core/widgets/scanner_view/scanner_entry.dart
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/onboarding/onboarding_legal_texts.dart
  apps/enmeshed/lib/profiles/device/widgets/device_onboarding_safety_note.dart
  packages/enmeshed_ui_kit/lib/src/utils/extensions.dart
Labels: bug

#407 UI Quickfixes
  apps/enmeshed/lib/account/contacts/modals/select_contacts_filters.dart
  apps/enmeshed/lib/account/mailbox/modals/select_mailbox_filters.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_or_identity.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile_or_identity_modal.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/should_delete_profile.dart
Labels: bug

#411 File detail screen uses a german date format
  apps/enmeshed/lib/account/my_data/file/file_detail_screen.dart
Labels: bug

#412 Whitelabel docs
  README_dev.md
Labels: documentation

#414 Bump runtime
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/attributes_facade_test.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/responses/can_create_repository_attribute.dart
  packages/enmeshed_types/lib/src/responses/responses.dart
Labels: dependencies

#416 Upgrade Runtime
  apps/enmeshed/pubspec.lock
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/pubspec.lock
  packages/enmeshed_runtime_bridge/lib/src/enmeshed_runtime.dart
  packages/enmeshed_runtime_bridge/lib/src/javascript_handlers.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_runtime_bridge/natives/src/ConfigAccess.ts
  packages/enmeshed_runtime_bridge/natives/src/DeviceInfoAccess.ts
  packages/enmeshed_runtime_bridge/natives/src/NativeBootstrapper.ts
  packages/enmeshed_runtime_bridge/natives/src/index.ts
  packages/enmeshed_runtime_bridge/pubspec.yaml
Labels: dependencies, refactoring

#418 Delete attribute modal is not as the other modals
  apps/enmeshed/lib/core/modals/delete_attribute.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/pubspec.lock
  packages/enmeshed_ui_kit/lib/enmeshed_ui_kit.dart
  packages/enmeshed_ui_kit/lib/src/bottom_sheets/bottom_sheet_header.dart
  packages/enmeshed_ui_kit/lib/src/bottom_sheets/bottom_sheets.dart
  packages/enmeshed_ui_kit/lib/src/bottom_sheets/conditional_closeable.dart
  packages/enmeshed_ui_kit/lib/src/widgets/bolt_styled_text.dart
  packages/enmeshed_ui_kit/lib/src/widgets/widgets.dart
  packages/enmeshed_ui_kit/pubspec.yaml
Labels: bug

#420 Improve Profiles Screen
  apps/enmeshed/ios/Podfile.lock
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
  packages/enmeshed_types/lib/src/contents/notification.dart
Labels: bug
