Repository nmshd/app, pull requests merged in 2025-04, with the labels that each got.

#498 Remove super calls
  packages/enmeshed_types/lib/src/contents/request_items/authentication_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/consent_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/create_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/delete_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/free_text_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/propose_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/read_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/register_attribute_listener_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/request_item_derivation.dart
  packages/enmeshed_types/lib/src/contents/request_items/request_item_group.dart
  packages/enmeshed_types/lib/src/contents/request_items/request_item_group.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/request_items.dart
  packages/enmeshed_types/lib/src/contents/request_items/share_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/transfer_file_ownership_request_item.dart
  packages/enmeshed_types/test/contents/request_item/request_item_derivation_test.dart
  packages/enmeshed_types/test/contents/request_item/request_item_test.dart
Labels: refactoring

#500 Bump agp
  packages/enmeshed_runtime_bridge/integration_test_runner/android/app/build.gradle
  packages/enmeshed_runtime_bridge/integration_test_runner/android/settings.gradle
Labels: chore

#484 Automatic logout off the app when current identity is in deletion
  apps/enmeshed/lib/account/account_screen.dart
  apps/enmeshed/lib/core/widgets/profile_card.dart
  apps/enmeshed/lib/core/widgets/widgets.dart
  apps/enmeshed/lib/identity_in_deletion_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/profiles/profile/widgets/profile_widgets.dart
Labels: enhancement

#504 Remove unnecessary reload of contact requests when current account is in deletion
  apps/enmeshed/lib/account/account_screen.dart
Labels: chore

#505 Update illustrations
  apps/enmeshed/assets/svg/add_contact.svg
  apps/enmeshed/assets/svg/attribute_deletion.svg
  apps/enmeshed/assets/svg/connect_with_contact.svg
  apps/enmeshed/assets/svg/instructions_load_existing_profile.svg
  apps/enmeshed/assets/svg/load_profile.svg
  apps/enmeshed/assets/svg/onboarding1.svg
  apps/enmeshed/assets/svg/onboarding2.svg
  apps/enmeshed/assets/svg/onboarding3.svg
  apps/enmeshed/assets/svg/remove_device.svg
  apps/enmeshed/lib/account/home/widgets/add_contact_or_device_container.dart
  apps/enmeshed/lib/main.dart
Labels: enhancement

#503 Theme switcher
  apps/enmeshed/lib/account/app_drawer/app_drawer.dart
  apps/enmeshed/lib/account/app_drawer/drawer_main_page.dart
  apps/enmeshed/lib/account/app_drawer/drawer_theme_page.dart
  apps/enmeshed/lib/core/core.dart
  apps/enmeshed/lib/core/modals/restore_identity.dart
  apps/enmeshed/lib/core/models/models.dart
  apps/enmeshed/lib/core/models/theme_mode_model.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/themes/themes.dart
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
Labels: enhancement

#512 Contact detail screen is not reloading the contact when the contact status changes
  apps/enmeshed/lib/account/contacts/contact_detail_screen.dart
  apps/enmeshed/lib/account/contacts/widgets/contact_detail_header.dart
  apps/enmeshed/lib/core/widgets/contact_circle_avatar.dart
Labels: bug

#510 Show modal bottom sheet when creating new profile in identity in deletion screen
  apps/enmeshed/lib/core/widgets/change_profile_picture.dart
  apps/enmeshed/lib/core/widgets/create_profile.dart
  apps/enmeshed/lib/core/widgets/widgets.dart
  apps/enmeshed/lib/identity_in_deletion_screen.dart
  apps/enmeshed/lib/profiles/profile/modals/edit_profile.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
  apps/enmeshed/lib/profiles/profile/select_profile_dialog.dart
  apps/enmeshed/lib/profiles/profile/widgets/profile_widgets.dart
Labels: refactoring

#514 Transfer file ownership items are wrong
  packages/enmeshed_types/lib/src/contents/response_items/transfer_file_ownership_accept_response_item.dart
  packages/enmeshed_types/lib/src/contents/response_items/transfer_file_ownership_accept_response_item.g.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.g.dart
Labels: bug

#516 Android navigation is dark in dark mode
  apps/enmeshed/lib/main.dart
Labels: bug

#517 Remove debug print
  apps/enmeshed/lib/main.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_consent_request_item_renderer.dart
Labels: chore

#518 Proper imports
  packages/renderers/lib/src/attribute/relationship_attribute_value_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_consent_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/request_item_renderer.dart
Labels: refactoring

#519 Improve German grammar
  apps/enmeshed/lib/l10n/app_de.arb
Labels: enhancement

#520 The device onboarding QR code is not visible in dark mode
  apps/enmeshed/lib/profiles/device/modals/device_onboarding.dart
Labels: bug

#524 Cards are not aligned with the text
  apps/enmeshed/lib/core/modals/create_recovery_kit/save_or_print_recovery_kit.dart
Labels: bug

#525 Expose validation result to the request renderer and all sub renderers
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
  packages/renderers/lib/src/request/request_item_group_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/request_item_renderer.dart
  packages/renderers/lib/src/request/request_renderer.dart
Labels: refactoring

#526 Add changes from TransferFileOwnership
  packages/renderers/lib/src/request/request_item_group_renderer.dart
  packages/renderers/lib/src/request/request_renderer.dart
Labels: bug

#527 Move FileIcon to UI kit
  apps/enmeshed/lib/core/widgets/file_chooser.dart
  apps/enmeshed/lib/core/widgets/file_item.dart
  apps/enmeshed/lib/core/widgets/upload_file.dart
  apps/enmeshed/lib/core/widgets/widgets.dart
  packages/enmeshed_ui_kit/lib/src/widgets/file_icon.dart
  packages/enmeshed_ui_kit/lib/src/widgets/widgets.dart
  packages/enmeshed_ui_kit/pubspec.yaml
Labels: refactoring

#530 Android notifications have no icon
  apps/enmeshed/android/app/src/main/AndroidManifest.xml
  apps/enmeshed/android/app/src/main/res/drawable-hdpi/notification.png
  apps/enmeshed/android/app/src/main/res/drawable-mdpi/notification.png
  apps/enmeshed/android/app/src/main/res/drawable-xhdpi/notification.png
  apps/enmeshed/android/app/src/main/res/drawable-xxhdpi/notification.png
  apps/enmeshed/android/app/src/main/res/drawable-xxxhdpi/notification.png
  apps/enmeshed/android/app/src/main/res/drawable/notification.png
  packages/enmeshed_runtime_bridge/integration_test_runner/android/app/src/main/res/drawable-hdpi/notification.png
  packages/enmeshed_runtime_bridge/integration_test_runner/android/app/src/main/res/drawable-mdpi/notification.png
  packages/enmeshed_runtime_bridge/integration_test_runner/android/app/src/main/res/drawable-xhdpi/notification.png
  packages/enmeshed_runtime_bridge/integration_test_runner/android/app/src/main/res/drawable-xxhdpi/notification.png
  packages/enmeshed_runtime_bridge/integration_test_runner/android/app/src/main/res/drawable-xxxhdpi/notification.png
  packages/enmeshed_runtime_bridge/integration_test_runner/android/app/src/main/res/drawable/notification.png
  packages/enmeshed_runtime_bridge/lib/src/javascript_handlers.dart
Labels: bug

#532 Re-enable Impeller
  apps/enmeshed/android/app/src/main/AndroidManifest.xml
Labels: chore

#531 Add Support for FormFieldRequestItem
  apps/enmeshed/assets/i18n/de.json
  apps/enmeshed/assets/i18n/en.json
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/analysis_options.yaml
  packages/enmeshed_types/lib/src/contents/request_items/form_field_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_settings/boolean_form_field_settings.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_settings/date_form_field_settings.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_settings/double_form_field_settings.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_settings/form_field_settings.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_settings/form_field_settings.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_settings/integer_form_field_settings.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_settings/rating_form_field_settings.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_settings/selection_form_field_settings.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_settings/string_form_field_settings.dart
  packages/enmeshed_types/lib/src/contents/request_items/request_item_derivation.dart
  packages/enmeshed_types/lib/src/contents/response_items/accept_response_item.dart
  packages/enmeshed_types/lib/src/contents/response_items/form_field_accept_response_item.dart
  packages/enmeshed_types/lib/src/contents/response_items/form_field_accept_response_item.g.dart
  packages/enmeshed_types/lib/src/dvos/consumption/decidable_request_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.g.dart
  packages/enmeshed_types/lib/src/requests/decide_request/accept_request/form_field.dart
Labels: dependencies

#533 Allow longer tags
  apps/enmeshed/assets/i18n/de.json
  apps/enmeshed/assets/i18n/en.json
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: enhancement

#534 Remove jscm teams messages
  codemagic.yaml
Labels: ci

#535 Respect denied mails
  apps/enmeshed/lib/account/contacts/widgets/contact_detail_icon_bar.dart
  apps/enmeshed/lib/account/mailbox/send_mail_screen/widgets/choose_contact.dart
  apps/enmeshed/lib/core/widgets/contact_circle_avatar.dart
  apps/enmeshed/lib/core/widgets/contact_item.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/dvos/transport/relationship_dvo.dart
  packages/enmeshed_types/lib/src/dvos/transport/relationship_dvo.g.dart
Labels: enhancement

#537 Shared with navigation is not clear
  apps/enmeshed/lib/account/my_data/all_data/attribute_detail_screen.dart
  apps/enmeshed/lib/account/my_data/file/file_detail_screen.dart
Labels: bug

#539 Remove outdated features
  apps/enmeshed/lib/account/contacts/contact_detail_screen.dart
  apps/enmeshed/lib/account/contacts/contacts_view.dart
  apps/enmeshed/lib/account/contacts/modals/modals.dart
  apps/enmeshed/lib/account/contacts/modals/request_certificate.dart
  apps/enmeshed/lib/account/contacts/widgets/contact_detail_icon_bar.dart
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: chore

#536 Rework consent request item renderer
  apps/enmeshed/assets/i18n/de.json
  apps/enmeshed/assets/i18n/en.json
  packages/connector_sdk/lib/src/endpoints/challenges_endpoint.dart
  packages/renderers/lib/src/request/request_item_renderer/consent_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_consent_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/widgets/validation_error_box.dart
  packages/renderers/lib/src/request/request_item_renderer/request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/transfer_file_ownership_request_item_renderer.dart
  packages/renderers/pubspec.yaml
  packages/renderers/test/renderers/request_item_renderer/consent_request_item_renderer_test.dart
  packages/value_renderer/lib/src/inputs/datepicker_input/datepicker_form_field.dart
Labels: enhancement

#542 Remove QR code use cases and make the runtime slimmer
  apps/enmeshed/assets/texts/legal_notice.md
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/files_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/relationship_template_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/tokens_facade_test.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/files_facade.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/relationship_templates_facade.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/tokens_facade.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/responses/create_qr_code.dart
  packages/enmeshed_types/lib/src/responses/responses.dart
  packages/enmeshed_types/test/responses/create_qr_code_test.dart
Labels: dependencies, refactoring

#546 Update imports and exports
  packages/enmeshed_types/lib/src/contents/request_items/request_items.dart
  packages/enmeshed_types/lib/src/contents/response_items/response_items.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.dart
  packages/enmeshed_types/lib/src/requests/decide_request/accept_request/form_field.dart
Labels: refactoring

#549 Bump runtime
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/account_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/relationship_template_facade_test.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/relationship_templates_facade.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: dependencies
