Repository nmshd/app, pull requests merged in 2025-07, with the labels that each got.

#689 Downgrade go_router due to retracted version
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
  packages/enmeshed_ui_kit/pubspec.yaml
  packages/renderers/pubspec.yaml
Labels: dependencies

#691 Update Runtime to support Announcement actions
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/js/package-lock.json
  packages/enmeshed_runtime_bridge/js/package.json
  packages/enmeshed_types/lib/src/dtos/announcement.dart
  packages/enmeshed_types/lib/src/dtos/announcement.g.dart
Labels: dependencies

#687 Show auto-accepted transfer files with unviewed indicator
  apps/enmeshed/lib/account/account_screen.dart
  apps/enmeshed/lib/account/contacts/contact_detail_screen.dart
  apps/enmeshed/lib/account/home/home.dart
  apps/enmeshed/lib/account/my_data/file/file_detail_screen.dart
  apps/enmeshed/lib/account/my_data/file/files_screen.dart
  apps/enmeshed/lib/account/my_data/my_data_view.dart
  apps/enmeshed/lib/core/utils/attribute_utils.dart
  apps/enmeshed/lib/core/widgets/file_item.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: enhancement

#700 The naming of shared data is reversed
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
Labels: bug

#705 Remove Attribute listeners
  apps/enmeshed/assets/i18n/de.json
  apps/enmeshed/assets/i18n/en.json
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/js/package-lock.json
  packages/enmeshed_runtime_bridge/js/package.json
  packages/enmeshed_runtime_bridge/lib/src/data_view_expander.dart
  packages/enmeshed_runtime_bridge/lib/src/services/consumption_services.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attribute_listeners_facade.dart
  packages/enmeshed_types/lib/src/contents/request_items/register_attribute_listener_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/register_attribute_listener_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/request_item_derivation.dart
  packages/enmeshed_types/lib/src/contents/request_items/request_items.dart
  packages/enmeshed_types/lib/src/contents/response_items/accept_response_item.dart
  packages/enmeshed_types/lib/src/contents/response_items/register_attribute_listener_accept_response_item.dart
  packages/enmeshed_types/lib/src/contents/response_items/register_attribute_listener_accept_response_item.g.dart
  packages/enmeshed_types/lib/src/contents/response_items/response_items.dart
  packages/enmeshed_types/lib/src/dtos/dtos.dart
  packages/enmeshed_types/lib/src/dtos/local_attribute_listener.dart
  packages/enmeshed_types/lib/src/dvos/consumption/consumption.dart
  packages/enmeshed_types/lib/src/dvos/consumption/local_attribute_listener_dvo.dart
  packages/enmeshed_types/lib/src/dvos/consumption/local_attribute_listener_dvo.g.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.g.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/response_item_dvos.g.dart
  packages/enmeshed_types/test/dtos/local_attribute_listener_test.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_register_attribute_listener_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/register_attribute_listener_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/request_item_renderers.dart
  packages/renderers/lib/src/request/request_item_renderer/response/register_attribute_lister_accept_response_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/response/response.dart
  packages/renderers/lib/src/request/request_item_renderer/response/response_item_renderer.dart
Labels: breaking-change

#711 Selecting a contact is possible on the send mail screen when a recipient is pre-selected
  apps/enmeshed/lib/account/mailbox/send_mail_screen/send_mail_screen.dart
  apps/enmeshed/lib/account/mailbox/send_mail_screen/widgets/choose_contact.dart
Labels: bug

#712 Logs can not be written in debug mode
  apps/enmeshed/lib/main.dart
Labels: bug

#713 Melos integration test script is not referencing the config from the correct path
  melos.yaml
Labels: chore

#715 Uploading a file results in an unviewed file
  apps/enmeshed/lib/core/widgets/upload_file.dart
Labels: bug

#704 Add feedback button
  apps/enmeshed/android/app/src/main/AndroidManifest.xml
  apps/enmeshed/assets/svg/feedback.svg
  apps/enmeshed/ios/Podfile.lock
  apps/enmeshed/ios/Runner/Info.plist
  apps/enmeshed/lib/account/app_drawer/drawer_hints_page.dart
  apps/enmeshed/lib/account/app_drawer/drawer_main_page.dart
  apps/enmeshed/lib/account/home/home.dart
  apps/enmeshed/lib/account/home/widgets/give_feedback_banner.dart
  apps/enmeshed/lib/account/home/widgets/home_widgets.dart
  apps/enmeshed/lib/core/modals/feedback/feedback.dart
  apps/enmeshed/lib/core/modals/feedback/feedback_error_dialog.dart
  apps/enmeshed/lib/core/modals/feedback/feedback_success_dialog.dart
  apps/enmeshed/lib/core/modals/modals.dart
  apps/enmeshed/lib/core/utils/feedback_utils.dart
  apps/enmeshed/lib/core/utils/settings_utils.dart
  apps/enmeshed/lib/core/utils/utils.dart
  apps/enmeshed/lib/core/widgets/instructions_screen.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/themes/feedback_theme.dart
  apps/enmeshed/lib/themes/themes.dart
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
  packages/enmeshed_ui_kit/lib/src/cards/information_card.dart
Labels: enhancement

#723 Bump runtime
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/js/package-lock.json
  packages/enmeshed_runtime_bridge/js/package.json
Labels: dependencies

#724 Audit fix
  packages/enmeshed_runtime_bridge/js/package-lock.json
Labels: dependencies

#729 Update Runtime to v7 alpha 55
  apps/enmeshed/assets/i18n/de.json
  apps/enmeshed/assets/i18n/en.json
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/attributes_facade_test.dart
  packages/enmeshed_runtime_bridge/js/package-lock.json
  packages/enmeshed_runtime_bridge/js/package.json
  packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
  packages/enmeshed_types/lib/src/contents/request_items/authentication_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/authentication_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/consent_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/consent_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/create_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/create_attribute_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/delete_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/delete_attribute_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/form_field_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/propose_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/propose_attribute_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/read_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/read_attribute_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/request_item_derivation.dart
  packages/enmeshed_types/lib/src/contents/request_items/share_attribute_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/share_attribute_request_item.g.dart
  packages/enmeshed_types/lib/src/contents/request_items/transfer_file_ownership_request_item.dart
  packages/enmeshed_types/lib/src/contents/request_items/transfer_file_ownership_request_item.g.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.dart
  packages/enmeshed_types/lib/src/dvos/content/request_item_dvos.g.dart
  packages/renderers/lib/src/request/request_item_renderer/authentication_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/consent_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/checkbox_enabled_extension.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_create_attribute_request_item.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_propose_attribute_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_read_attribute_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_share_attribute_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/extensions/extensions.dart
  packages/renderers/lib/src/request/request_item_renderer/transfer_file_ownership_request_item_renderer.dart
  packages/renderers/lib/src/request/request_item_renderer/widgets/manual_decision_required.dart
Labels: breaking-change

#721 Refine feedback functionality
  apps/enmeshed/ios/Podfile.lock
  apps/enmeshed/lib/account/app_drawer/app_drawer.dart
  apps/enmeshed/lib/account/app_drawer/drawer_main_page.dart
  apps/enmeshed/lib/account/home/home.dart
  apps/enmeshed/lib/account/home/widgets/give_feedback_banner.dart
  apps/enmeshed/lib/core/modals/feedback/feedback_error_dialog.dart
  apps/enmeshed/lib/core/modals/feedback/feedback_success_dialog.dart
  apps/enmeshed/lib/core/utils/feedback_utils.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
Labels: enhancement

#735 Show announcements on home screen
  apps/enmeshed/lib/account/account_screen.dart
  apps/enmeshed/lib/account/home/home.dart
  apps/enmeshed/lib/account/home/widgets/announcements_container.dart
  apps/enmeshed/lib/account/home/widgets/home_widgets.dart
  apps/enmeshed/lib/account/my_data/my_data_view.dart
  apps/enmeshed/lib/core/utils/attribute_utils.dart
  packages/enmeshed_types/lib/src/dtos/announcement.dart
  packages/enmeshed_types/lib/src/dtos/announcement.g.dart
Labels: enhancement

#740 Store app data in a folder for the current alpha release
  apps/enmeshed/lib/drawer/debug_screen.dart
  apps/enmeshed/lib/onboarding/onboarding_welcome.dart
  apps/enmeshed/lib/splash_screen.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/setup.dart
  packages/enmeshed_runtime_bridge/js/src/index.ts
  packages/enmeshed_runtime_bridge/lib/src/enmeshed_runtime.dart
Labels: breaking-change

#742 Download file operation can be destroyed until the next app restart when using multiple file operations in the same time
  apps/enmeshed/lib/account/my_data/file/file_detail_screen.dart
Labels: bug
