Repository nmshd/app, pull requests merged in 2025-05, with the labels that each got.

#550 Some tag translations are missing
  apps/enmeshed/assets/i18n/de.json
  apps/enmeshed/assets/i18n/en.json
  apps/enmeshed/lib/account/my_data/file/file_detail_screen.dart
Labels: bug

#551 Enable predictive back on android
  apps/enmeshed/android/app/src/main/AndroidManifest.xml
  apps/enmeshed/lib/themes/themes.dart
Labels: enhancement

#552 Update imprint
  apps/enmeshed/assets/texts/imprint.md
Labels: chore

#555 Consistent test group naming
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/data_view_expander_test/message_dvo_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/anonymous/anonymous_tokens_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/anonymous/backbone_compatibility_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/attributes_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/settings_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/account_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/devices_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/files_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/identity_recovery_kits_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/messages_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/public_relationship_template_references_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/relationship_template_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/relationships_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/tokens_facade_test.dart
Labels: test

#556 Migrate from dependabot to renovate
  .github/dependabot.yml
  .github/renovate.json5
Labels: ci

#558 broken renovate config
  .github/renovate.json5
Labels: ci

#564 Do not update the dart SDK
  .github/renovate.json5
Labels: ci

#570 Major version upgrades
  apps/enmeshed/android/app/build.gradle
  apps/enmeshed/android/gradle/wrapper/gradle-wrapper.properties
  apps/enmeshed/android/settings.gradle
  apps/enmeshed/ios/Podfile.lock
  apps/enmeshed/lib/account/contacts/widgets/dismissible_contact_item.dart
  apps/enmeshed/lib/core/setup_push.dart
  apps/enmeshed/lib/core/widgets/scanner_view/scanner_entry.dart
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
  apps/enmeshed/windows/flutter/generated_plugins.cmake
  packages/enmeshed_runtime_bridge/integration_test_runner/android/app/build.gradle
  packages/enmeshed_runtime_bridge/integration_test_runner/android/gradle/wrapper/gradle-wrapper.properties
  packages/enmeshed_runtime_bridge/integration_test_runner/android/settings.gradle
  packages/enmeshed_runtime_bridge/integration_test_runner/pubspec.lock
  packages/enmeshed_runtime_bridge/integration_test_runner/windows/flutter/generated_plugins.cmake
  packages/enmeshed_runtime_bridge/pubspec.yaml
  packages/enmeshed_ui_kit/lib/src/utils/extensions.dart
  packages/identity_recovery_kit/example/android/.gitignore
  packages/identity_recovery_kit/example/android/app/build.gradle
  packages/identity_recovery_kit/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/identity_recovery_kit/example/android/settings.gradle
Labels: dependencies

#571 Update lockfiles
  apps/enmeshed/pubspec.yaml
  packages/enmeshed_runtime_bridge/integration_test_runner/pubspec.lock
  packages/enmeshed_runtime_bridge/integration_test_runner/pubspec.yaml
  packages/identity_recovery_kit/example/pubspec.lock
Labels: dependencies

#573 Ignore not found maven plugin
  .github/renovate.json5
Labels: ci

#574 match using regex
  .github/renovate.json5
Labels: ci

#575 The app crashes on Android
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
Labels: bug

#580 Add support for url references
  apps/enmeshed/assets/i18n/de.json
  apps/enmeshed/assets/i18n/en.json
  apps/enmeshed/lib/account/contacts/widgets/discoverable_identities.dart
  apps/enmeshed/lib/core/modals/create_recovery_kit/create_recovery_kit.dart
  apps/enmeshed/lib/core/modals/error_dialog.dart
  apps/enmeshed/lib/core/widgets/scanner_view/url_entry.dart
  apps/enmeshed/lib/core/widgets/upload_file.dart
  apps/enmeshed/lib/profiles/device/modals/device_onboarding.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/anonymous/anonymous_tokens_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/consumption/requests_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/account_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/files_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/relationship_template_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/relationships_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/tokens_facade_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/string_processor_test.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/utils.dart
  packages/enmeshed_runtime_bridge/integration_test_runner/ios/Podfile.lock
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/account_facade.dart
  packages/enmeshed_runtime_bridge/lib/src/string_processor.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_types/lib/src/dtos/dtos.dart
  packages/enmeshed_types/lib/src/dtos/file.dart
  packages/enmeshed_types/lib/src/dtos/file.g.dart
  packages/enmeshed_types/lib/src/dtos/object_reference.dart
  packages/enmeshed_types/lib/src/dtos/object_reference.g.dart
  packages/enmeshed_types/lib/src/dtos/relationship_template.dart
  packages/enmeshed_types/lib/src/dtos/relationship_template.g.dart
  packages/enmeshed_types/lib/src/dtos/token.dart
  packages/enmeshed_types/lib/src/dtos/token.g.dart
  packages/enmeshed_types/lib/src/dvos/transport/file_dvo.dart
  packages/enmeshed_types/lib/src/dvos/transport/file_dvo.g.dart
  packages/enmeshed_types/lib/src/responses/load_item_from_reference.dart
  packages/enmeshed_types/lib/src/responses/load_item_from_truncated_reference.dart
  packages/enmeshed_types/lib/src/responses/responses.dart
  packages/enmeshed_types/test/dtos/message_with_attachments_test.dart
  packages/enmeshed_types/test/dtos/relationship_template_test.dart
  packages/enmeshed_types/test/dtos/token_test.dart
  packages/enmeshed_types/test/responses/challenge_validation_result_test.dart
  packages/enmeshed_types/test/responses/load_item_from_truncated_reference_test.dart
  packages/value_renderer/lib/src/renderers/file_reference.dart
Labels: enhancement

#586 Remove connector UI build script
  .github/workflows/build_connector_ui.yml
  apps/enmeshed/tools/push.md
Labels: chore

#587 Remove developer from debugging entitlements
  apps/enmeshed/ios/Runner/RunnerDebug.entitlements
  apps/enmeshed/ios/Runner/RunnerProfile.entitlements
Labels: chore

#590 Update ios config
  apps/enmeshed/ios/Runner.xcodeproj/project.pbxproj
Labels: chore

#594 Bump runtime
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: dependencies

#595 Add share file to file detail screen
  apps/enmeshed/ios/Podfile.lock
  apps/enmeshed/lib/account/my_data/file/file_detail_screen.dart
  apps/enmeshed/lib/core/utils/file_utils.dart
  apps/enmeshed/pubspec.lock
  apps/enmeshed/pubspec.yaml
  apps/enmeshed/windows/flutter/generated_plugin_registrant.cc
  apps/enmeshed/windows/flutter/generated_plugins.cmake
  packages/renderers/lib/src/custom_list_tile.dart
Labels: enhancement

#597 Do not process nmshd links anymore
  apps/enmeshed/android/app/src/main/AndroidManifest.xml
  apps/enmeshed/ios/Runner/Info.plist
  apps/enmeshed/lib/core/modals/create_recovery_kit/create_recovery_kit.dart
  apps/enmeshed/lib/core/widgets/scanner_view/url_entry.dart
  apps/enmeshed/lib/profiles/device/modals/device_onboarding.dart
  apps/enmeshed/lib/splash_screen.dart
  apps/enmeshed/pubspec.yaml
  apps/enmeshed/tools/appLinks.md
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/string_processor_test.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/identity_recovery_kit/example/lib/main.dart
Labels: breaking-change

#599 Upgrade backbone
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
  .github/renovate.json5
  .github/workflows/runtime_bridge_integration_tests.yml
Labels: ci

#602 Allow getting announcements via app runtime
  README_dev.md
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/services/facades/transport/announcements_facade_test.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport.dart
  packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/announcements_facade.dart
  packages/enmeshed_runtime_bridge/lib/src/services/transport_services.dart
  packages/enmeshed_types/lib/src/dtos/announcement.dart
  packages/enmeshed_types/lib/src/dtos/announcement.g.dart
  packages/enmeshed_types/lib/src/dtos/dtos.dart
Labels: enhancement

#607 Cancelling the password prompt shows an error in the app
  apps/enmeshed/pubspec.lock
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: bug

#610 Auto select single account in requestAccountSelection
  apps/enmeshed/lib/core/app_ui_bridge.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: enhancement

#611 Use different scanners for templates and device onboarding
  apps/enmeshed/lib/core/utils/settings_utils.dart
  apps/enmeshed/lib/core/widgets/scan_recovery_kit_screen.dart
  apps/enmeshed/lib/core/widgets/scan_screen.dart
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/onboarding/onboarding_account.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/string_processor_test.dart
  packages/enmeshed_runtime_bridge/lib/src/string_processor.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
Labels: enhancement

#616 The method to fetch the push token is way to complicated
  apps/enmeshed/lib/core/setup_push.dart
  apps/enmeshed/lib/splash_screen.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/integration_test_runner/integration_test/setup.dart
  packages/enmeshed_runtime_bridge/lib/src/enmeshed_runtime.dart
  packages/enmeshed_runtime_bridge/lib/src/javascript_handlers.dart
  packages/enmeshed_runtime_bridge/lib/src/ui_bridge.dart
  packages/enmeshed_runtime_bridge/natives/package-lock.json
  packages/enmeshed_runtime_bridge/natives/package.json
  packages/enmeshed_runtime_bridge/natives/src/ConfigAccess.ts
  packages/enmeshed_runtime_bridge/natives/src/NativeBootstrapper.ts
  packages/enmeshed_runtime_bridge/natives/src/NotificationAccess.ts
  packages/enmeshed_runtime_bridge/natives/src/globals.d.ts
  packages/enmeshed_runtime_bridge/natives/src/index.ts
  packages/enmeshed_runtime_bridge/natives/src/uiBridge.ts
Labels: bug

#618 Add the ability to scan the recovery kit from the profiles screen
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/profiles/profile/profiles_screen.dart
Labels: enhancement

#606 Legal texts are skipped when opening the app with a link
  apps/enmeshed/lib/account/my_data/file/file_detail_screen.dart
  apps/enmeshed/lib/core/utils/account_utils.dart
  apps/enmeshed/lib/core/widgets/create_profile.dart
  apps/enmeshed/lib/core/widgets/modal_loading_overlay.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/main.dart
  apps/enmeshed/lib/onboarding/onboarding_app_link_available.dart
  apps/enmeshed/lib/onboarding/onboarding_create_account.dart
  apps/enmeshed/lib/onboarding/onboarding_information.dart
  apps/enmeshed/lib/onboarding/onboarding_legal_texts.dart
  apps/enmeshed/lib/onboarding/onboarding_screen.dart
  apps/enmeshed/lib/onboarding/onboarding_select_option.dart
  apps/enmeshed/lib/onboarding/onboarding_welcome.dart
  apps/enmeshed/lib/profiles/profile/select_profile_dialog.dart
  apps/enmeshed/lib/splash_screen.dart
Labels: bug

#621 Generate json methods for LocalRequest
  packages/enmeshed_types/lib/src/dtos/local_request.dart
  packages/enmeshed_types/lib/src/dtos/local_request.g.dart
  packages/enmeshed_types/lib/src/dtos/local_response.dart
  packages/enmeshed_types/lib/src/dtos/local_response.g.dart
  packages/enmeshed_types/lib/src/dtos/local_response_source.dart
  packages/enmeshed_types/lib/src/dtos/local_response_source.g.dart
  packages/enmeshed_types/test/dtos/local_request_source_test.dart
  packages/enmeshed_types/test/dtos/local_request_test.dart
  packages/enmeshed_types/test/dtos/local_response_source_test.dart
  packages/enmeshed_types/test/dtos/local_response_test.dart
Labels: refactoring

#635 Consistent loading overlays
  apps/enmeshed/lib/core/modals/create_recovery_kit/enter_password.dart
  apps/enmeshed/lib/core/modals/restore_identity.dart
  apps/enmeshed/lib/core/widgets/modal_loading_overlay.dart
  apps/enmeshed/lib/core/widgets/upload_file.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  apps/enmeshed/lib/profiles/device/device_detail/widgets/delete_device_sheet.dart
  apps/enmeshed/lib/profiles/device/modals/create_device.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/delete_profile.dart
  apps/enmeshed/lib/profiles/profile/modals/delete_profile/deleting_profile.dart
  apps/enmeshed/lib/profiles/profile/modals/edit_profile.dart
Labels: enhancement

#637 Bump runtime
  apps/enmeshed/lib/splash_screen.dart
  packages/enmeshed_runtime_bridge/assets/index.js
  packages/enmeshed_runtime_bridge/js/package-lock.json
  packages/enmeshed_runtime_bridge/js/package.json
  packages/enmeshed_runtime_bridge/js/src/DatabaseFactory.ts
  packages/enmeshed_runtime_bridge/js/src/FileAccess.ts
  packages/enmeshed_runtime_bridge/js/src/NativeBootstrapper.ts
  packages/enmeshed_runtime_bridge/js/src/NotificationAccess.ts
  packages/enmeshed_runtime_bridge/js/src/globals.d.ts
  packages/enmeshed_runtime_bridge/js/src/index.ts
  packages/enmeshed_runtime_bridge/lib/src/enmeshed_runtime.dart
Labels: dependencies

#627 Enhance Request and Message rendering
  apps/enmeshed/lib/account/mailbox/mailbox_view.dart
  apps/enmeshed/lib/account/mailbox/message_detail_screen.dart
  apps/enmeshed/lib/core/widgets/message_dvo_renderer.dart
  apps/enmeshed/lib/core/widgets/message_list_tile.dart
  apps/enmeshed/lib/core/widgets/messages_container.dart
  apps/enmeshed/lib/core/widgets/request_dvo_renderer.dart
  apps/enmeshed/lib/core/widgets/widgets.dart
  apps/enmeshed/lib/l10n/app_de.arb
  apps/enmeshed/lib/l10n/app_en.arb
  packages/enmeshed_types/lib/src/dvos/content/request_dvo.dart
  packages/enmeshed_types/lib/src/dvos/content/request_dvo.g.dart
  packages/enmeshed_ui_kit/lib/src/utils/custom_colors.dart
Labels: enhancement

#639 Add FloatingActionButton for QR scanning on account screen
  apps/enmeshed/lib/account/account_screen.dart
  apps/enmeshed/lib/account/home/home.dart
  apps/enmeshed/lib/account/home/widgets/add_contact.dart
  apps/enmeshed/lib/account/home/widgets/home_widgets.dart
  apps/enmeshed/lib/themes/themes.dart
Labels: enhancement
